// frontend/src/app/layout.js
import './globals.css'; // <--- ต้องมีบรรทัดนี้
import { Inter } from 'next/font/google';
import Navbar from '../components/Navbar';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* ไม่มี <style jsx global> block */}
        <Navbar />
        {children}
      </body>
    </html>
  );
}